apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: itzchaktunik-dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 27017
  selector:
    app: mongodb